DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE IF NOT EXISTS users (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome             VARCHAR(255),
    email            VARCHAR(255),
    descricao        VARCHAR(255),
    streak_num       INTEGER,
    streak_status    INTEGER,
    ultima_atividade TIMESTAMP(6),
    senha            VARCHAR(255)
);